schedules:
  - cron: '0 0 * * 0'
    displayName: weekly build
    branches:
      include:
      - master
    always: true

jobs:
  - job: MSYS
    timeoutInMinutes: 360
    pool:
      vmImage: 'windows-2019'
    strategy:
      maxParallel: 5
      matrix:
        x86_64:
          MSYS_DIR: msys64
          BASE_REPO: msys2-ci-base
          ARCH: x86_64
    steps:
      - script: |
          git clone https://github.com/msys2/$(BASE_REPO).git %CD:~0,2%\$(MSYS_DIR)
        displayName: Install MSYS2
      - script: |
          set PATH=%CD:~0,2%\$(MSYS_DIR)\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\pacman --noconfirm -Syyuu
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\pacman --noconfirm -Syuu
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\pacman --noconfirm -S p7zip
        displayName: Update MSYS2
      - script: |
          set CHERE_INVOKING=yes
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\$(MSYS_DIR)\usr\bin\bash -lc "bash make-msys2-installer; cp msys2-base-$(ARCH)-[0-9]*.sfx.exe msys2-base-$(ARCH)-latest.sfx.exe; cp msys2-$(ARCH)-[0-9]*.exe msys2-$(ARCH)-latest.exe; cp msys2-*.tar.xz msys2-base-$(ARCH)-latest.tar.xz"
        displayName: CI-Build
      - task: CopyFiles@2
        inputs:
          contents: 'msys2-*'
          targetFolder: $(Build.ArtifactStagingDirectory)
        displayName: Copy installer
      - task: GithubRelease@0
        inputs:
          githubConnection: 'msys2-installer-release-connection'
          action: 'edit'
          tag: nightly-$(ARCH)
          assets: '$(Build.ArtifactStagingDirectory)/*'
          assetUploadMode: 'delete'
          addChangeLog: false
        displayName: 'Create GitHub Release'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest'))
      - task: PublishBuildArtifacts@1
        displayName: Publish packages
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: $(MSYS_DIR)
        condition: and(succeeded(), or(ne(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'PullRequest')))
